"""
G-code Generator for Hyperspectral Scanning
=============================================
Generates raster scan G-code files compatible with OpenBuilds/GRBL.

Usage:
    # Reproduce the existing 1cm x 1cm, 0.2mm step, 2s dwell file:
    python gcode_generator.py --x-end 10 --y-end 10 --step 0.2 --dwell 2 -o scan.gcode

    # 5mm x 5mm, 0.5mm step, snake pattern:
    python gcode_generator.py --x-end 5 --y-end 5 --step 0.5 --dwell 2 --snake -o scan.gcode

    # Just preview the scan stats without writing:
    python gcode_generator.py --x-end 10 --y-end 10 --step 0.2 --dwell 2 --info
"""

import argparse
from pathlib import Path

import numpy as np


def generate_gcode(
    x_start: float,
    x_end: float,
    x_step: float,
    y_start: float,
    y_end: float,
    y_step: float,
    dwell_time: float,
    feedrate: int = 1000,
    initial_dwell: float = 4.0,
    snake: bool = False,
) -> tuple[str, int]:
    """
    Generate raster scan G-code.

    Returns:
        (gcode_string, total_positions)
    """
    xs = np.arange(x_start, x_end + x_step * 0.5, x_step)
    ys = np.arange(y_start, y_end + y_step * 0.5, y_step)
    total = len(xs) * len(ys)
    est_minutes = total * (dwell_time + 0.3) / 60

    lines = [
        f"; Hyperspectral Scan G-code",
        f"; Generated by gcode_generator.py",
        f"; X: {x_start} to {x_end} mm, step {x_step} mm ({len(xs)} points)",
        f"; Y: {y_start} to {y_end} mm, step {y_step} mm ({len(ys)} points)",
        f"; Total positions : {total}",
        f"; Dwell per point : {dwell_time} s",
        f"; Estimated time  : {est_minutes:.1f} min",
        f"; Pattern         : {'snake (boustrophedon)' if snake else 'left-to-right raster'}",
        f"",
        f"G90 ; Absolute positioning",
        f"",
        f"; Move to start and settle",
        f"G01 X{x_start:.4f} Y{y_start:.4f} F{feedrate}",
        f"G04 P{int(initial_dwell)}",
        f"",
    ]

    for i, y in enumerate(ys):
        row = xs if not snake or i % 2 == 0 else xs[::-1]
        for x in row:
            lines.append(f"G01 X{x:.4f} Y{y:.4f} F{feedrate}")
            lines.append(f"G04 P{int(dwell_time)}")

    return "\n".join(lines), total


def main():
    parser = argparse.ArgumentParser(
        description="G-code generator for hyperspectral raster scans",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--x-start", type=float, default=0.0,  metavar="MM")
    parser.add_argument("--x-end",   type=float, default=10.0, metavar="MM")
    parser.add_argument("--x-step",  type=float, default=0.2,  metavar="MM")
    parser.add_argument("--y-start", type=float, default=0.0,  metavar="MM")
    parser.add_argument("--y-end",   type=float, default=10.0, metavar="MM")
    parser.add_argument("--y-step",  type=float, default=0.2,  metavar="MM")
    parser.add_argument("--step",    type=float, default=None,
                        help="Set both --x-step and --y-step at once")
    parser.add_argument("--dwell",   type=float, default=2.0,
                        help="Dwell time per position in seconds")
    parser.add_argument("--feedrate", type=int,  default=1000, metavar="MM/MIN")
    parser.add_argument("--initial-dwell", type=float, default=4.0,
                        help="Extra settle time at the first position (seconds)")
    parser.add_argument("--snake", action="store_true",
                        help="Snake (boustrophedon) pattern: alternate row direction to reduce travel")
    parser.add_argument("-o", "--output", default=None,
                        help="Output file path. Prints to stdout if omitted.")
    parser.add_argument("--info", action="store_true",
                        help="Print scan statistics and exit without generating G-code")

    args = parser.parse_args()

    x_step = args.step if args.step is not None else args.x_step
    y_step = args.step if args.step is not None else args.y_step

    if args.info:
        import numpy as np
        xs = np.arange(args.x_start, args.x_end + x_step * 0.5, x_step)
        ys = np.arange(args.y_start, args.y_end + y_step * 0.5, y_step)
        total = len(xs) * len(ys)
        print(f"X points  : {len(xs)}  ({args.x_start} to {args.x_end} mm, step {x_step} mm)")
        print(f"Y points  : {len(ys)}  ({args.y_start} to {args.y_end} mm, step {y_step} mm)")
        print(f"Total     : {total} positions")
        print(f"Dwell     : {args.dwell} s/position")
        print(f"Est. time : {total * (args.dwell + 0.3) / 60:.1f} min")
        return

    gcode, total = generate_gcode(
        x_start=args.x_start, x_end=args.x_end, x_step=x_step,
        y_start=args.y_start, y_end=args.y_end, y_step=y_step,
        dwell_time=args.dwell,
        feedrate=args.feedrate,
        initial_dwell=args.initial_dwell,
        snake=args.snake,
    )

    if args.output:
        Path(args.output).write_text(gcode, encoding="utf-8")
        print(f"Saved {total} positions to {args.output}")
    else:
        print(gcode)


if __name__ == "__main__":
    main()
